import type { MenuItem } from "@/lib/types"

export const menuData: {
  appetizers: MenuItem[]
  mainCourses: MenuItem[]
  desserts: MenuItem[]
  beverages: MenuItem[]
} = {
  appetizers: [
    {
      id: "app-1",
      name: "Garlic Bread",
      description: "Freshly baked bread with garlic butter and herbs.",
      price: 5.99,
      image: "/images/aaptiz bread.avif",
      category: "appetizers",
    },
    {
      id: "app-2",
      name: "Mozzarella Sticks",
      description: "Golden fried mozzarella sticks served with marinara.",
      price: 7.99,
      image: "/images/apptiz m-stick.avif",
      category: "appetizers",
    },
    {
      id: "app-3",
      name: "Chicken Wings",
      description: "Crispy chicken wings tossed in your choice of sauce.",
      price: 9.99,
      image: "/images/apptiz chekn wing.avif",
      category: "appetizers",
    },
    {
      id: "app-4",
      name: "Loaded Nachos",
      description: "Tortilla chips topped with cheese, jalapeños, and sour cream.",
      price: 8.99,
      image: "/images/apptiz cheesecake.avif",
      category: "appetizers",
    },
    {
      id: "app-5",
      name: "Calamari",
      description: "Lightly breaded and fried calamari served with aioli sauce.",
      price: 10.99,
      image: "/images/farabic-dishes.avif",
      category: "appetizers",
    },
    {
      id: "app-6",
      name: "Spinach Artichoke Dip",
      description: "Creamy spinach and artichoke dip served with tortilla chips.",
      price: 8.49,
      image: "/images/apptiz grilled.avif",
      category: "appetizers",
    },
  ],
  mainCourses: [
    {
      id: "main-1",
      name: "Classic Cheeseburger",
      description: "Angus beef patty with cheddar, lettuce, tomato, and special sauce.",
      price: 12.99,
      image: "/images/apptiz burger.webp",
      category: "main-courses",
    },
    {
      id: "main-2",
      name: "Grilled Salmon",
      description: "Fresh Atlantic salmon with lemon butter sauce and seasonal vegetables.",
      price: 18.99,
      image: "/images/apptiz chesecake.avif",
      category: "main-courses",
    },
    {
      id: "main-3",
      name: "Chicken Alfredo",
      description: "Fettuccine pasta with grilled chicken in a creamy Alfredo sauce.",
      price: 15.99,
      image: "/images/apptiz tiramis.avif",
      category: "main-courses",
    },
    {
      id: "main-4",
      name: "Margherita Pizza",
      description: "Classic pizza with tomato sauce, fresh mozzarella, and basil.",
      price: 14.99,
      image: "/images/apptiz c-burger.webp",
      category: "main-courses",
    },
    {
      id: "main-5",
      name: "Steak Frites",
      description: "Grilled ribeye steak with garlic butter and crispy french fries.",
      price: 22.99,
      image: "/images/fried-chicken.avif",
      category: "main-courses",
    },
    {
      id: "main-6",
      name: "Vegetable Stir Fry",
      description: "Fresh vegetables stir-fried in a savory sauce with steamed rice.",
      price: 13.99,
      image: "/images/apptiz crumbed-fish-sticks.jpg",
      category: "main-courses",
    },
  ],
  desserts: [
    {
      id: "dessert-1",
      name: "Chocolate Lava Cake",
      description: "Warm chocolate cake with a molten center, served with vanilla ice cream.",
      price: 7.99,
      image: "/images/oreo-cheesecake.jpg",
      category: "desserts",
    },
    {
      id: "dessert-2",
      name: "New York Cheesecake",
      description: "Creamy cheesecake with a graham cracker crust and berry compote.",
      price: 6.99,
      image: "/images/premium-cake.avif",
      category: "desserts",
    },
    {
      id: "dessert-3",
      name: "Tiramisu",
      description: "Italian dessert with layers of coffee-soaked ladyfingers and mascarpone.",
      price: 8.49,
      image: "/images/apptiz pasta.avif",
      category: "desserts",
    },
    {
      id: "dessert-4",
      name: "Apple Pie",
      description: "Homemade apple pie with a flaky crust, served warm with ice cream.",
      price: 6.49,
      image: "/images/cake-1.avif",
      category: "desserts",
    },
  ],
  beverages: [
    {
      id: "bev-1",
      name: "Fresh Lemonade",
      description: "Freshly squeezed lemonade with a hint of mint.",
      price: 3.99,
      image: "/images/cocktail.jpg",
      category: "beverages",
    },
    {
      id: "bev-2",
      name: "Iced Tea",
      description: "House-brewed iced tea, sweetened or unsweetened.",
      price: 2.99,
      image: "/images/iced-latte-.jpg",
      category: "beverages",
    },
    {
      id: "bev-3",
      name: "Craft Soda",
      description: "Artisanal sodas in various flavors.",
      price: 3.49,
      image: "/images/premium_photo.avif",
      category: "beverages",
    },
    {
      id: "bev-4",
      name: "Espresso",
      description: "Double shot of our premium espresso blend.",
      price: 3.99,
      image: "/images/iced-coffee.jpg",
      category: "beverages",
    },
  ],
}
